version: '3.1'

services:

  fristaskmanagerbackend:
    depends_on:
      - db
    image: fernandoris/fris_task_manager_backend:0.0.1-SNAPSHOT
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    links:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=fristaskmanager
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080