version: '3.1'

services:

  fristaskmanagerbackend:
    depends_on:
      - db
    image: fernandoris/fris_task_manager_backend:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    links:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080